depth:
  type: None
pose:
  learn_pose: True
dataloading:
  path: data/Tanks
  scene: ['Horse']
  customized_focal: False
  random_ref: 1
training:
  out_dir:  out/Tanks/Horse
  auto_scheduler: True
extract_images:
  resolution: [540, 960]